### ISSUE TITLE
npm 依赖error

### ISSUE THREAD

**Issue by ghost** [leenty/vue2#7]
亲。跑不起来。 Windows 下 无论是 npm install  还是您的教程 npn i  都是报错的  项目跑不起来 怎么解决哟
![npm i error](https://user-images.githubusercontent.com/16719884/29812275-9d8f921a-8cd8-11e7-82e8-2910147c1c8a.png)
![npm install error](https://user-images.githubusercontent.com/16719884/29812276-9da41f1e-8cd8-11e7-9676-4486f897111b.png)

**Comment by leenty** [comment]
看下node和npm的版本，如果太低了更新下。
不行的话把报错完整的贴出来。
建议下次issue可以附带的贴出node和npm还有操作系统版本，这样容易找到问题。

**Comment by ghost** [comment]
非常感谢  麻烦您再看下
![error](https://user-images.githubusercontent.com/16719884/29814907-7dea0dd8-8ce1-11e7-8171-38c0a3439fee.png)
![windows](https://user-images.githubusercontent.com/16719884/29814908-7e04a666-8ce1-11e7-9d09-4c3d1b778fae.png)

**Comment by leenty** [comment]
昨天回去装了个windows的虚拟机测试，没有遇到你的问题，但是遇到了其他依赖的错误。
现在已经把多余且错误的依赖去掉了。可以拉一下代码然后尝试安装下。
![image](https://user-images.githubusercontent.com/13213680/29852880-35241b96-8d6f-11e7-9885-766ec86f20ed.png)

如果依赖包下不下来，可以使用vpn或者[淘宝镜像](http://npm.taobao.org/)

**Comment by ghost** [comment]
亲。依赖现在产生新的错误。 
![new error](https://user-images.githubusercontent.com/16719884/29853445-9424da6a-8d72-11e7-919b-a518de97115c.png)
如果方便 能否委屈下 加下联系方式。。 放心，我不会问关于这个项目之外的麻烦你 WQQ 75879446

**Comment by leenty** [comment]
哈哈哈好的，你怎么还有错误，我的虚拟机完美运行了😂，我加你吧
